# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='author',
            new_name='owner',
        ),
    ]
