# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20180610_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='published_date',
            new_name='change_date',
        ),
    ]
