# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_auto_20180610_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='created_date',
            new_name='create_date',
        ),
    ]
