# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 12:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('structure', '0004_auto_20180613_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='editors',
            field=models.ManyToManyField(related_name='_table_editors_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
