# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_table_editors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='editors',
            field=models.ManyToManyField(related_name='editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='table',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
