# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 12:45
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_auto_20180617_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='table_body',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
